# config/config.yaml

api:
  github_base_url: "https://data.gharchive.org"

azure:
  file_system: "raw-events"

ingestion:
  lookback_hours: 3  # How many hours ago to fetch data
  retry_delay_minutes: 10  # For future retry logic

paths:
  raw_data_prefix: "year={year}/month={month}/day={day}/data_{hour_str}.json.gz"
