version: 2

sources:
  - name: dbo         
    database: githubpool           
    schema: dbo                     
    tables:
      - name: github_events         
        description: "Cleaned GitHub events data from the Warehouse"
        
        columns:
          - name: id
            description: "Unique event ID from GitHub API"
            data_tests:
              - unique
              - not_null

          - name: type
            description: "Event type (e.g., PushEvent, PullRequestEvent)"
            data_tests:
              - not_null
              - accepted_values:
                  values: ['PushEvent', 'PullRequestEvent', 'IssuesEvent', 'CreateEvent', 'ReleaseEvent' , 'IssueCommentEvent' , 'PullRequestReviewCommentEvent']
            
          - name: actor_login
            description: "GitHub username of the actor"
            data_tests:
              - not_null
            
          - name: repo_name
            description: "Repository name where the event occurred"
            data_tests:
              - not_null
            
          - name: created_at_ts
            description: "Timestamp of when the event was created"
            data_tests:
              - not_null

          